# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

test:pytest:
  stage: test
  image: python:3.9
  script:
    - pip install pytest --quiet
    - PYTHONPATH=`pwd`/scripts pytest -v tests/

test:
  stage: test
  image: node:10
  before_script:
    - npm install gitbook-cli -g # install gitbook
    - gitbook fetch 3.2.3 # fetch final stable version
    - gitbook install # add any requested plugins in book.json
    - python3.9 scripts/build_all_report_pages.py
  script:
    - cd public
    - gitbook build . public # build to public path
    - cp -r public/* .
    - rm -r public
  only:
    - branches # this job will affect every branch except 'master'
  except:
    - master

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  image: node:10
  before_script:
    - npm install gitbook-cli -g # install gitbook
    - gitbook fetch 3.2.3 # fetch final stable version
    - gitbook install # add any requested plugins in book.json
    - python3.9 scripts/build_all_report_pages.py
  script:
    - cd public
    - gitbook build . public # build to public path
    - cp -r public/* .
    - rm -r public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master # this job will affect only the 'master' branch
