stages:
  - pretest
  - build
  - test
  - deploy

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

pytest:
  stage: pretest
  image: python:3.9
  script:
    - pip install pytest --quiet
    - PYTHONPATH=`pwd`/python pytest -v tests/
    - python setup.py install --user

build:
  stage: build
  image: python:3.9
  script:
    - PYTHONPATH=`pwd`/python ./python/Test_Reporting/build_all_report_pages.py 2>&1 | tee public/build.log
  artifacts:
    paths:
      - public
    expire_in: 1 day

pages-test:
  stage: test
  image: node:10
  before_script:
    - npm install gitbook-cli -g # install gitbook
    - gitbook fetch 3.2.3 # fetch final stable version
    - gitbook install # add any requested plugins in book.json
  script:
    - cd public
    - gitbook build . test_output # build to test path
    - mv test_output ../
    - cd ..
    - mv public test_input
  artifacts:
    paths:
      - test_input
      - test_output
    expire_in: 1 week
  only:
    - branches # this job will affect every branch except 'master'
  except:
    - master

PEP8:
  stage: test
  image:
    name: alpine/flake8
    entrypoint: [ '' ]
  script:
    - flake8 --max-line-length 120 python/Test_Reporting
  only:
    - branches # this job will affect every branch except 'master'
  except:
    - master

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  image: node:10
  before_script:
    - npm install gitbook-cli -g # install gitbook
    - gitbook fetch 3.2.3 # fetch final stable version
    - gitbook install # add any requested plugins in book.json
  script:
    - cd public
    - gitbook build . public # build to public path
    - cp -r public/* .
    - rm -r public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master # this job will affect only the 'master' branch
